# Generated by Django 4.0.6 on 2022-07-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_booking_dep_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='dep_name',
        ),
    ]
